import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { GEN_DIR, LAST_MANIFEST, MIGRATIONS_DIR } from "./paths.mjs";

const MIGRATION_RE = /^(\d{3})_.+\.sql$/;

export async function nextSequence() {
  let max = 0;
  try {
    for (const name of await readdir(MIGRATIONS_DIR)) {
      const match = MIGRATION_RE.exec(name);
      if (match) max = Math.max(max, Number(match[1]));
    }
  } catch {
    max = 0;
  }
  return max + 1;
}

export function formatSeq(n) {
  return String(n).padStart(3, "0");
}

export function stamp() {
  return new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 14);
}

export async function writeMigration({ seq, slug, sql, expect }) {
  await mkdir(MIGRATIONS_DIR, { recursive: true });
  await mkdir(GEN_DIR, { recursive: true });
  const version = `${formatSeq(seq)}_${slug}`;
  const fileName = `${version}.sql`;
  const filePath = path.join(MIGRATIONS_DIR, fileName);
  const header = `-- generated by do-migration @ ${new Date().toISOString()}\n-- expect: ${JSON.stringify(expect)}\n\n`;
  await writeFile(filePath, header + sql.trim() + "\n", "utf8");

  const manifest = {
    version,
    file: fileName,
    createdAt: new Date().toISOString(),
    expect,
  };
  await writeFile(LAST_MANIFEST, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  return manifest;
}

export async function readLastManifest() {
  try {
    const raw = await readFile(LAST_MANIFEST, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/** 每次调用都产生**新文件**的变更（工具本身不幂等）。 */
export async function generateAutoTick() {
  const seq = await nextSequence();
  const tag = stamp();
  const column = `mig_${formatSeq(seq)}`;
  const rowName = `auto-${formatSeq(seq)}-${tag}`;
  const defaultValue = `tick-${formatSeq(seq)}-${tag}`;

  const sql = `
alter table items add column ${column} text not null default '${defaultValue}';

insert into items (name, status, ${column})
values ('${rowName}', 'active', '${defaultValue}');
`;

  const manifest = await writeMigration({
    seq,
    slug: `auto_${tag}`,
    sql,
    expect: {
      migrationVersion: `${formatSeq(seq)}_auto_${tag}`,
      itemsColumnsIncludes: [column],
      itemNamesIncludes: [rowName],
      itemFieldEquals: { name: rowName, field: column, value: defaultValue },
    },
  });

  return manifest;
}

export async function generateAddColumn(column, sqlType = "text") {
  const seq = await nextSequence();
  const tag = stamp();
  const safe = column.replace(/[^a-zA-Z0-9_]/g, "");
  if (!safe) throw new Error("列名无效");
  const defaultLiteral = `col-${formatSeq(seq)}-${tag}`;

  const sql = `
alter table items add column ${safe} ${sqlType} not null default '${defaultLiteral}';
`;

  return writeMigration({
    seq,
    slug: `add_${safe}_${tag}`,
    sql,
    expect: {
      migrationVersion: `${formatSeq(seq)}_add_${safe}_${tag}`,
      itemsColumnsIncludes: [safe],
    },
  });
}

export async function generateInsertItem(name) {
  const seq = await nextSequence();
  const tag = stamp();
  const rowName = name ?? `manual-${formatSeq(seq)}-${tag}`;

  const sql = `
insert into items (name, status)
values ('${rowName.replace(/'/g, "''")}', 'active');
`;

  return writeMigration({
    seq,
    slug: `insert_${tag}`,
    sql,
    expect: {
      migrationVersion: `${formatSeq(seq)}_insert_${tag}`,
      itemNamesIncludes: [rowName],
    },
  });
}
