concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "874222d98137"
  url = "http://10.1.10.220:6060"
  id = 72
  token = "glrt-3Z9UQAneV1Kbox_3-WVSzG86MQp0OjEKdToxCw.01.120g7ufym"
  token_obtained_at = 2026-04-03T04:10:45Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["GIT_SSL_NO_VERIFY=true"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "node-git"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    pull_policy = ["if-not-present"]
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
