name: Build and Tests
on:
  - push
  - pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: pnpm install
      - run: npm run build
      - run: npm run test
