# docker build -t std-cli-base:latest ./

FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
