[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Alice <a@example.com>", "Bob <b@example.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.12"
