
# job1
job1-f: [ -d "job1-website" ] && cd job1-website/ && yarn startClient
job1-s: [ -d "job1-server" ] && cd job1-server/ && yarn startServer

# job2
job2: [ -d "job2-monitor" ] && cd job2-monitor && job2.sh


job3: echo "waiting for 3000 server start" && until lsof -i -P -n | grep "3000.*LISTEN" > /dev/null 2>&1 ; do sleep 3; done && echo "start job3"
